<?php

namespace Plugi\Extensions\Form;

use Plugi\Repositories\BaseRepository;

class DefinitionsRepository extends BaseRepository {
    /**
     * The uploads database table.
     *
     * @var string
     */
    protected $table = 'ext__form_definitions';

    public function create(array $data): null|object|array
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }
    public function update($instance, array $data)
    {
        return parent::update($instance, $data); // TODO: Change the autogenerated stub
    }
}
